apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskmanager

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres-configmap.yaml
  - postgres-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ingress-basic.yaml

# You can use kustomize to deploy:
# kubectl apply -k .

